name: pulsetrade_app
description: Production-ready Flutter app scaffolded with Clean Architecture and Riverpod 3.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  flutter_riverpod: ^3.0.0-dev.3
  riverpod: ^3.0.0-dev.3
  riverpod_annotation: ^3.0.0-dev.3
  go_router: ^14.2.8
  fpdart: ^0.6.0
  equatable: ^2.0.5
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  dio: ^5.4.3+1
  connectivity_plus: ^6.0.3
  shared_preferences: ^2.3.2
  flutter_secure_storage: ^9.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_form_builder: ^10.0.1
  form_builder_validators: ^11.1.2
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.10
  flutter_tabler_icons: ^1.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.11
  freezed: ^2.4.4
  json_serializable: ^6.8.0
  riverpod_generator: ^3.0.0-dev.3
  custom_lint: ^0.5.11
  riverpod_lint: ^3.0.0-dev.3
  mocktail: ^1.0.3
  flutter_lints: ^4.0.0

dependency_overrides:
  analyzer: 6.4.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
